### ISSUE TITLE
NullPointerException when uploading

### ISSUE THREAD

**Issue by chruetli** [software-competence-center-hagenberg/NodeDoc#7]
Hi

When I try to upload a file generated by the nodeset compiler (model.NodeSet2.xml) there is a NullPointerException. Is there something obvious wrong?

```
nodedoc-1  | 2024-10-11 06:23:30.705  INFO 1 --- [nio-5010-exec-2] at.scch.opcua.service.NodesetService     : Save NodeSet from multipart file
nodedoc-1  | 2024-10-11 06:23:30.705  INFO 1 --- [nio-5010-exec-2] a.s.nodedoc.ModelFileSystemRepository    : Save NodeSet from InputStream
nodedoc-1  | 2024-10-11 06:23:30.706  INFO 1 --- [nio-5010-exec-2] at.scch.nodedoc.parser.NodeSetXMLParser  : Parse and validate XML
nodedoc-1  | java.lang.NullPointerException
nodedoc-1  | 	at at.scch.nodedoc.ModelFileSystemRepository.getNodeSetDirectory(ModelFileSystemRepository.java:35)
nodedoc-1  | 	at at.scch.nodedoc.ModelFileSystemRepository.saveNodeSet(ModelFileSystemRepository.java:67)
nodedoc-1  | 	at at.scch.opcua.service.NodesetService.saveNodeSetFromMultipartFile(NodesetService.java:59)
nodedoc-1  | 	at at.scch.opcua.controller.NodesetController.saveNodesetWithoutGeneratingDocumentation(NodesetController.java:29)
nodedoc-1  | 	at at.scch.opcua.controller.NodesetController$$FastClassBySpringCGLIB$$27246d48.invoke(<generated>)
nodedoc-1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
nodedoc-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
nodedoc-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
nodedoc-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
nodedoc-1  | 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
nodedoc-1  | 	at at.scch.opcua.demomode.DemoRestrictionAspect.intercept(DemoRestrictionAspect.java:24)
nodedoc-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nodedoc-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
nodedoc-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
nodedoc-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
nodedoc-1  | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
nodedoc-1  | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
nodedoc-1  | 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
nodedoc-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
nodedoc-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
nodedoc-1  | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
nodedoc-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
nodedoc-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
nodedoc-1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
nodedoc-1  | 	at at.scch.opcua.controller.NodesetController$$EnhancerBySpringCGLIB$$901a579c.saveNodesetWithoutGeneratingDocumentation(<generated>)
nodedoc-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nodedoc-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
nodedoc-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
nodedoc-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
nodedoc-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
nodedoc-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
nodedoc-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
nodedoc-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
nodedoc-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
nodedoc-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
nodedoc-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
nodedoc-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
nodedoc-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
nodedoc-1  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
nodedoc-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
nodedoc-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
nodedoc-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
nodedoc-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
nodedoc-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
nodedoc-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
nodedoc-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
nodedoc-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
nodedoc-1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
nodedoc-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
nodedoc-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
nodedoc-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
nodedoc-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
nodedoc-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
nodedoc-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
nodedoc-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
nodedoc-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
nodedoc-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
nodedoc-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
nodedoc-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
nodedoc-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
nodedoc-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
nodedoc-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
nodedoc-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
nodedoc-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
nodedoc-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
nodedoc-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by bdorninger** [comment]
Can you provide the nodeset?
Might be that there is no publication date in the file.
Anyway, this should not result in an error

**Comment by chruetli** [comment]
Indeed there was no `Version`/`PublicationDate` attribute in the `Model` tag. Now it's green! 👍 
Thank you!

**Comment by bdorninger** [comment]
PubDate and Versionare optional attributes - so we need to address this.
Thanks for pointing this out
